////////////////////////////////////////////////////////////////////////////
//
// Copyright 2025 Realm Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
////////////////////////////////////////////////////////////////////////////


@Component
export struct TouchDisplayer {
  @State currentTouches: TouchObject[] = []
  @State touchIndicatorOpacity: number = 0
  @BuilderParam buildChildren: () => void
  build() {
    Stack() {
      this.buildChildren()
      ForEach(this.currentTouches, (activeTouch: TouchObject) => {
        Stack() {
        }
        .width(64)
        .height(64)
        .backgroundColor("blue")
        .borderWidth(2)
        .borderColor("white")
        .opacity(this.touchIndicatorOpacity)
        .position({ x: activeTouch.x - 32, y: activeTouch.y - 32 })
        .borderRadius(1000)
        .hitTestBehavior(HitTestMode.Transparent)
      })
    }
    .width("100%")
    .height("100%")
    .hitTestBehavior(HitTestMode.Transparent)
    .onTouch(e => {
      this.currentTouches = e.touches
      this.touchIndicatorOpacity = 0.5
      animateTo({
        duration: 500,
        curve: Curve.Linear,
      }, () => {
        this.touchIndicatorOpacity = 0
      })
    })
  }
}